#
# CONFIGURATION GENERALE
#

EXEC = progGraphe
OBJETS = graphe.o liste.o outilsGraphe.o outilsListe.o pl.o file.o
NOM_PROJET = 501_tp5

#
# SUFFIXES
#

.SUFFIXES: .c .o

#
# OBJETS
#

EXEC_O = $(EXEC:=.o)
OBJETS_O = $(OBJETS) $(EXEC_O)

#
# ARGUMENTS ET COMPILATEUR
#
# CCFLAGS = -Wall -O3 -Wpadded -Werror -ansi -pedantic

CC = gcc
CCFLAGS = -Wall -O3
CCLIBS = 

#
# REGLES
#

all: $(OBJETS) $(EXEC_O)
	@echo "Creation des executables..."
	@for i in $(EXEC); do \
	$(CC) -o $$i $$i.o $(OBJETS) $(CCLIBS); \
	done
	@echo "Termine."

#
# REGLES PAR DEFAUT
#

.c.o: .h
	@cd $(dir $<) && ${CC} ${CCFLAGS} -c $(notdir $<) -o $(notdir $@)

#
# REGLES GENERALES
#

clean:
	@echo "Suppresion des objets, des fichiers temporaires..."
	@rm -f $(OBJETS) $(EXEC_O)
	@rm -f *~ *#
	@rm -f $(EXEC)
	@rm -f dependances
	@echo "Termine."

depend:
	@echo "Creation des dependances..."
	@sed -e "/^# DEPENDANCES/,$$ d" makefile > dependances
	@echo "# DEPENDANCES" >> dependances
	@for i in $(OBJETS_O); do \
	$(CC) -MM -MT $$i $(CCFLAGS) `echo $$i | sed "s/\(.*\)\\.o$$/\1.c/"` >> dependances; \
	done
	@cat dependances > makefile
	@rm dependances
	@echo "Termine."

#
# CREATION ARCHIVE
#

ARCHIVE_FILES = *

archive: clean
	@echo "Creation de l'archive $(NOM_PROJET)$(shell date '+%y%m%d.tar.gz')..."
	@REP=`basename $$PWD`; cd .. && tar zcf $(NOM_PROJET)$(shell date '+%y%m%d.tar.gz') $(addprefix $$REP/,$(ARCHIVE_FILES))
	@echo "Termine."

# DEPENDANCES
graphe.o: graphe.c outilsGraphe.h graphe.h liste.h outilsListe.h
liste.o: liste.c liste.h
outilsGraphe.o: outilsGraphe.c outilsGraphe.h graphe.h liste.h \
 outilsListe.h
outilsListe.o: outilsListe.c outilsListe.h liste.h
pl.o: pl.c pl.h graphe.h liste.h file.h
file.o: file.c graphe.h liste.h file.h pl.h
progGraphe.o: progGraphe.c pl.h graphe.h liste.h outilsGraphe.h \
 outilsListe.h
